### ISSUE TITLE
setting CKA_ID

### ISSUE THREAD

**Issue by chetagra** [aws-samples/aws-cloudhsm-pkcs11-examples#66]
![Screenshot from 2023-04-11 16-17-40](https://user-images.githubusercontent.com/46901115/231139217-6cca3780-51cc-46b2-b878-e6245b73cb45.png)
I am getting following issue when trying to add CKA_ID value 

bellow is the code I am using 
![Screenshot from 2023-04-11 16-24-49](https://user-images.githubusercontent.com/46901115/231139588-31ef7e55-591f-4bc5-af7c-a33f12a65280.png)

**Comment by rday** [comment]
Hi @chetagra , there is an example of using hexadecimal to initialize an array here: https://github.com/aws-samples/aws-cloudhsm-pkcs11-examples/blob/master/src/generate/rsa_generate.c#L38. It may be easier if you paste your code instead of the screenshot, easier to reference! Good luck!

**Comment by chetagra** [comment]
can anyone provide any update on my above issue

**Comment by rday** [comment]
Hi chetagra@,
This problem was addressed in the other issue you opened (#68), in which you successfully created an EC key with a CKA_ID. We are only able to assist with problems related to the sample code.

To address your further requirements, could you reach out to AWS Developer Support, or post on [re:Post](https://repost.aws/questions) with the "AWS CloudHSM" tag. You will receive better support for your custom workflow using those methods.
